# docker-compose.yml
version: "3.8"

services:
  api:
    build: .
    container_name: taskrouter_api
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://user:pass@db:5432/taskrouter
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: taskrouter_worker
    command: ["python", "worker.py"]
    environment:
      - DB_URL=postgresql://user:pass@db:5432/taskrouter
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    container_name: taskrouter_db
    environment:
      POSTGRES_DB: taskrouter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: taskrouter_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
